### ISSUE TITLE
[Enhancement] Build out Users Page

### ISSUE THREAD

**Issue by abanuelo** [cascaritaco/cascarita#141]
Goal is to build out the remaining parts of the users page
<img width="1858" alt="Screenshot 2024-10-24 at 12 17 38 AM" src="https://github.com/user-attachments/assets/551b2b0e-a1fd-4b06-ad83-d020d3dc06fa">

**Comment by abanuelo** [comment]
Feel free to tag your PR to this issue @alonso-ov !

**Comment by alonso-ov** [comment]
[Pull Request #146](https://github.com/cascaritaco/cascarita/pull/146)

@abanuelo 👍👍👍!
